### ISSUE TITLE
Use Sundials rather than home brewed solvers?

### ISSUE THREAD

**Issue by idontgetoutmuch** [lawmurray/LibBi#44]
I highly recommend switching to https://computation.llnl.gov/projects/sundials rather than rolling your own. We have just switched to it from using the gnu scientific library and got a x2-3 speedup as well as really good diagnostics when the solver fails. Also http://mc-stan.org use it.

**Comment by lawmurray** [comment]
Noted, but not on the radar at the moment. It's worth saying that the solvers in LibBi were not rolled in haste either:

Murray, L.M. GPU Acceleration of Runge--Kutta Integrators. IEEE Transactions on Parallel and Distributed Systems, 2012, 23, 94-101.

**Comment by idontgetoutmuch** [comment]
I didn't mean in any way to imply they were rolled in haste - I can see from the code they were carefully constructed. I am about to submit a PR either.
